sudo: required
dist: trusty
language: generic
addons:
  apt:
    packages:
      - emscripten
script:
  - make
  - make test
deploy:
  skip_cleanup: true
  provider: script
  script: make deploy
  on:
    branch: master
