sudo: false
language: cpp
compiler:
  - clang
script:
  - make
  - make test
after_success:
  - make gh-pages
  - cd gh-pages
  - git init
  - git config user.name "Travis CI"
  - git config user.email "travis-ci@travis-ci.org"
  - git add .
  - git commit -m "Deploy to GitHub Pages"
