sudo: required
dist: trusty
language: generic
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get install -y emscripten
  - emconfigure
script:
  - make
  - make test
deploy:
  skip_cleanup: true
  provider: script
  script: make deploy
  on:
    branch: master
