sudo: false
language: cpp
addons:
  apt:
    packages:
      - build-essential
      - cmake
      - python2.7
      - nodejs
      - default-jre
compiler:
  - clang
install:
  - make emscripten
  - source emsdk_portable/emsdk_env.sh
script:
  - make
  - make test
deploy:
  skip_cleanup: true
  provider: script
  script: make deploy
  on:
    branch: master
